on:
  push:
    tags:
      - 'v*.*.*-rc*'
name: Create Pre-Release

jobs:
  build:
    name: Create Pre-Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Remove unwanted files
        run: |
          Remove-Item -Recurse -Force .github
          Remove-Item -Recurse -Force images
          Remove-Item -Force .gitignore

      - name: Compress files
        run: |
          Get-Location | Compress-Archive -DestinationPath UnlimitedPower.zip -Force
  
      - name: Deploy Pre-Release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: UnlimitedPower.zip
          tags: true
          prerelease: true
          draft: false
          branches: dev